version: 2

cache-defaults: &cache-defaults
  keys:
    - oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}
cache-cypress: &cache-cypress
  keys:
    - oid-cypress-v1-{{ arch }}-{{ checksum "yarn.lock" }}
aliases:
  - &cache-modules
    key: oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}
    paths: &cache-modules-paths
      - ~/.cache/yarn
      - node_modules
      # Necessary so that linting is faster on CI
      - .eslintcache
  - &cache-cypress-modules
    key: oid-cypress-v1-{{ arch }}-{{ checksum "yarn.lock" }}
    paths: &cache-cypress-paths
      - ~/.cache/Cypress
  - &yarn
    name: Installing Dependencies
    command: yarn install --non-interactive --frozen-lockfile --cache-folder ~/.cache/yarn
jobs:
  release:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - save_cache: *cache-modules
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "lshadler13@gmail.com" && git config --global user.name "lshadler"'
      - run:
          name: Auto Info
          command: yarn auto info
      - run:
          name: Auto Shipit
          command: |
            yarn release
workflows:
  version: 2
  commit-workflow:
    jobs:
      - release